[build]
  command = "npm run build-all"
  publish = "frontend/dist"
  functions = "backend/functions"

[build.environment]
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
